"""Port d’accés a assets i recursos binaris de només lectura."""
from typing import Protocol
from terralab3d.domain.identifiers import ResourceId

class BinaryAssetPort(Protocol):
    def open_readonly(self, resource_id: ResourceId) -> memoryview: ...
    def version(self, resource_id: ResourceId) -> int: ...
    def close(self, resource_id: ResourceId) -> None: ...
