"""Ports per a documents editables de l’usuari."""
from typing import Protocol
from terralab3d.domain.constellations.models import EditableConstellation
from terralab3d.domain.measurements.models import Measurement

class UserDocumentPort(Protocol):
    def load_constellations(self) -> tuple[EditableConstellation, ...]: ...
    def save_constellations(self, values: tuple[EditableConstellation, ...]) -> None: ...
    def load_measurements(self) -> tuple[Measurement, ...]: ...
    def save_measurements(self, values: tuple[Measurement, ...]) -> None: ...
