"""Ports de persistència de preferències i documents d’usuari."""
from typing import Any, Protocol, Sequence
from terralab3d.domain.identifiers import ResourceId, VariantId
from terralab3d.domain.constellations.models import EditableConstellation
from terralab3d.domain.resources.models import (
    ResourceDescriptor,
    ResourceInstallState,
)
from terralab3d.domain.datasets.models import FontTerritorial, SourceRole

class PreferencesPort(Protocol):
    def load_text(self, key: str) -> str | None: ...
    def save_text(self, key: str, value: str) -> None: ...

class ConstellationRepositoryPort(Protocol):
    def load_all(self) -> Sequence[EditableConstellation]: ...
    def save_all(self, constellations: Sequence[EditableConstellation]) -> None: ...


class DataSourceRepositoryPort(Protocol):
    def snapshot(self) -> dict[str, Any]: ...
    def elevation_records(self) -> tuple[dict[str, Any], ...]: ...
    def activate_elevation(self, source: dict[str, Any]) -> tuple[str, ...]: ...
    def restore_elevation_order(self, source_ids: tuple[str, ...]) -> None: ...
    def land_cover_records(self) -> tuple[dict[str, Any], ...]: ...
    def territorial_sources(self) -> tuple[FontTerritorial, ...]: ...
    def active_land_cover_source_id(self) -> str | None: ...
    def activate_land_cover(self, source: dict[str, Any]) -> str: ...
    def restore_land_cover_source(self, source_id: str | None) -> None: ...
    def configure_semantic_source(
        self,
        source_id: str,
        *,
        source_role: SourceRole,
        enabled: bool,
        priority: int,
    ) -> None: ...
    def remove(self, source_id: str) -> dict[str, Any] | None: ...


class ResourceCatalogWriterPort(Protocol):
    def get_descriptor(self, resource_id: ResourceId) -> ResourceDescriptor | None: ...
    def upsert(self, descriptor: ResourceDescriptor) -> None: ...
    def remove(self, resource_id: ResourceId) -> ResourceDescriptor | None: ...


class ResourceInstallationWriterPort(Protocol):
    def snapshot(self) -> dict[str, dict[str, Any]]: ...
    def set_resource_state(
        self,
        resource_id: ResourceId,
        state: ResourceInstallState,
        variant_id: VariantId,
        resolved_path: str | None = None,
        downloaded_bytes: int = 0,
        verified_at: str | None = None,
        error_message: str | None = None,
        manifest_data: dict[str, Any] | None = None,
    ) -> None: ...
    def remove_resource_state(self, resource_id: ResourceId, variant_id: VariantId) -> None: ...
