"""Ports de persistència de preferències i documents d’usuari."""
from typing import Protocol, Sequence
from terralab3d.domain.constellations.models import EditableConstellation

class PreferencesPort(Protocol):
    def load_text(self, key: str) -> str | None: ...
    def save_text(self, key: str, value: str) -> None: ...

class ConstellationRepositoryPort(Protocol):
    def load_all(self) -> Sequence[EditableConstellation]: ...
    def save_all(self, constellations: Sequence[EditableConstellation]) -> None: ...
