"""Ports d’execució i cancel·lació de tasques."""
from collections.abc import Callable
from typing import Protocol, TypeVar

T = TypeVar("T")

class CancellationToken(Protocol):
    def cancelled(self) -> bool: ...
    def raise_if_cancelled(self) -> None: ...

class TaskRunnerPort(Protocol):
    def submit(self, operation_id: str, task: Callable[[CancellationToken], T]) -> None: ...
    def cancel(self, operation_id: str) -> None: ...
    def close(self) -> None: ...
