"""Port d’observabilitat sense un framework de logging concret."""
from typing import Protocol

class TelemetryPort(Protocol):
    def counter(self, name: str, value: int, *, capability: str) -> None: ...
    def timing_ms(self, name: str, value_ms: float, *, capability: str) -> None: ...
    def error(self, code: str, message: str, *, capability: str) -> None: ...
