"""Contractes de casos d’ús de l’aplicació."""
from typing import Protocol
from terralab3d.application.events import ApplicationEvent

class LifecycleUseCases(Protocol):
    """Coordina aquesta capacitat sense importar adaptadors ni APIs gràfiques."""
    def start(self) -> tuple[ApplicationEvent, ...]: ...
    def suspend(self) -> tuple[ApplicationEvent, ...]: ...
    def resume(self) -> tuple[ApplicationEvent, ...]: ...
    def close(self) -> tuple[ApplicationEvent, ...]: ...
